name: Lint Code

on:
  push:
    branches: [master, main]
  pull_request:
    branches: [master, main]

jobs:
  lint_python:
    name: Lint Python Files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python 3.12
        uses: actions/setup-python@v5
        with:
          python-version: 3.12

      - name: Install flake8
        run: pip install flake8

      - name: Run flake8
        run: flake8 . --config .flake8

  lint_js:
    name: Lint JavaScript Files
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Node.js 20.x
        uses: actions/setup-node@v4
        with:
          node-version: 20.x

      - name: Install JSHint
        run: npm install -g jshint

      - name: Run JSHint
        run: jshint --config .jshintrc --exclude-path .gitignore .
          echo "✅ Linted all JavaScript files successfully"
